name: cicd-microservice-image

on: 
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: jop1rlzcopdemo.azurecr.io
  ACR_NAME: jop1rlzcopdemo
  ACR_USERNAME: e0a0b9a6-7559-48a1-b1cc-e7567b84f02e
  ACR_PASSWORD: ${{secrets.ACR_PASSWORD}}
  IMAGE_NAME: demomicroservice
  AZURE_WEBAPP_NAME: jop1rlz-demo

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to the Container registry
        run: | 
          az acr login -n ${{env.ACR_NAME}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./demo-microservice
          push: true
          tags: ${{env.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:${{ github.sha }}
      - name: Azure logout
        run: |
          az logout
          
  deploy-image-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:latest
          
      - name: Azure logout
        run: |
          az logout
