name: nestjs-image

on: 
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: jop1rlzcopdemo.azurecr.io
  ACR_USERNAME: jop1rlzcopdemo
  ACR_PASSWORD: ${{secrets.ACR_PASSWORD}}
  IMAGE_NAME: demomicroservice

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./demo-microservice
          push: true
          tags: latest
